// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO-hv9Gx04Q7JAxbcSXgmIQVPuBkuvLok',
    appId: '1:81346965660:web:6c8c23201d532d11a63d59',
    messagingSenderId: '81346965660',
    projectId: 'prm393-project',
    authDomain: 'prm393-project.firebaseapp.com',
    storageBucket: 'prm393-project.firebasestorage.app',
    measurementId: 'G-8RHZ1FHGBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8pv9c5O1j1FqWXEB7j93uUWlC0HpYYLs',
    appId: '1:81346965660:android:3ff3ff04ce3535a5a63d59',
    messagingSenderId: '81346965660',
    projectId: 'prm393-project',
    storageBucket: 'prm393-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUo2rZnieQ3n4v6SzwpjZapW-r488br-U',
    appId: '1:81346965660:ios:c13059e4297ac09aa63d59',
    messagingSenderId: '81346965660',
    projectId: 'prm393-project',
    storageBucket: 'prm393-project.firebasestorage.app',
    iosClientId: '81346965660-h6cu5ooq2det4hh27ioof2f37hejelnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.prm393Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUo2rZnieQ3n4v6SzwpjZapW-r488br-U',
    appId: '1:81346965660:ios:c13059e4297ac09aa63d59',
    messagingSenderId: '81346965660',
    projectId: 'prm393-project',
    storageBucket: 'prm393-project.firebasestorage.app',
    iosClientId: '81346965660-h6cu5ooq2det4hh27ioof2f37hejelnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.prm393Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO-hv9Gx04Q7JAxbcSXgmIQVPuBkuvLok',
    appId: '1:81346965660:web:a4574582ec3bf464a63d59',
    messagingSenderId: '81346965660',
    projectId: 'prm393-project',
    authDomain: 'prm393-project.firebaseapp.com',
    storageBucket: 'prm393-project.firebasestorage.app',
    measurementId: 'G-88HZ9G1HPQ',
  );
}
