name: Build APK and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release

      # 🔥 Tạo / update release cố định
      - name: Create or Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest APK
          files: build/app/outputs/flutter-apk/app-release.apk
          draft: false
          prerelease: false
#          replace_assets: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}